### ISSUE TITLE
What about function.bind?

### ISSUE THREAD

**Issue by pke** [troch/react-thunk#1]
How about this pattern I use often?

``` es6
class NameField extends React.Component {
  constructor(props) {
    super(props)
    this.onChange = event => props.setName(event.currentTarget.value)
    // Alternative: this.onChange2 = this.onChange2.bind(this)
  }
  onChange2(event) {
    this.props.setName(event.currentTarget.value)
  }
  render() {
    return <input onChange={this.onChange} /*onChange={this.onChange2}*//>
  }
}
```

And for stateless components the handler comes from the parent component anyway.

**Comment by troch** [comment]
The very common pattern you describe forces you to use a class.

> And for stateless components the handler comes from the parent component anyway.

If `setName` is a redux action you inject to a component using `connect` from react-redux, then you might not have a parent component to bind your event handler.

**Comment by pke** [comment]
Ok I get it. So you wouldn't recommend stateless components at all cause they can be not pure?

**Comment by troch** [comment]
No I recommend functional stateless components.
